export const strings = {
  en: {
    action_blocked: "Action Blocked for Your Protection",
    security_review: "Security Review Required",
    action_approved: "Transaction Approved",
    confirm_after_review: "Confirm After Review",
    cancel_action: "Cancel Action",
    fraud_warning_title: "Fraud Warning",
    helpline_message: "Contact Your Private Banker",
    cooling_off_message: "Cooling-off period active",
    proceed: "Proceed",
    blocked: "ACTION BLOCKED",
    warning: "CAUTION REQUIRED",
    safe: "SAFE ACTION",
    close_logout: "Close and Logout",
    wait: "Wait",
    proceed_anyway: "Proceed Anyway",
    high_risk: "High Probability Fraud Detected",
    elevated_risk: "Elevated Risk",
    low_risk: "Low Risk",
    security_intercept: "Security Intercept",
    account_restricted: "Your account has been temporarily restricted to prevent unauthorized movement of funds.",
    
    // Core Layout
    dashboard: "Dashboard",
    goals: "Goals",
    netWorth: "Net Worth",
    net_worth: "Net Worth",
    portfolio: "Portfolio",
    alertsRisk: "Alerts & Risk",
    alerts_risk: "Alerts & Risk",
    savings: "Savings",
    trending: "Trending",
    inPortfolio: "In portfolio",
    in_portfolio: "In portfolio",
    bullish: "Bullish",
    bearish: "Bearish",
    neutral: "Neutral",
    allow: "ALLOW",
    warn: "WARN",
    block: "BLOCK",
    healthScore: "Health Score",
    health_score: "Health Score",
    marketNews: "Market News",
    market_news: "Market News",
    capitalOutflow: "Capital Outflow",
    capital_outflow: "Capital Outflow",
    savingsVelocity: "Savings Velocity",
    savings_velocity: "Savings Velocity",
    trending_stocks: "Trending Stocks",
    cumulative_growth: "Cumulative growth",
    allocation_priority: "Allocation priority",
    growthTrajectory: "Growth Trajectory",
    growth_trajectory: "Growth Trajectory",
    coreHoldings: "Core Holdings",
    portfolioStrategy: "Portfolio Strategy",
    executerebalance: "Execute Rebalance",
    exportLedger: "Export Ledger",
    intelligenceReport: "Intelligence Report",
    darkMode: "Dark Mode",
    language: "Language",

    // Stocks
    RELIANCE: "RELIANCE",
    "Reliance Industries": "Reliance Industries",
    GOLDBEES: "GOLDBEES",
    "Nippon India Gold BeES ETF": "Nippon India Gold BeES ETF",
    "Gold BeES ETF": "Gold BeES ETF",
    HDFCBANK: "HDFCBANK",
    "HDFC Bank Ltd": "HDFC Bank Ltd",
    TCS: "TCS",
    "Tata Consultancy Services": "Tata Consultancy Services",
    INFY: "INFY",
    "Infosys Ltd": "Infosys Ltd",
    SUNPHARMA: "SUNPHARMA",
    "Sun Pharmaceutical Industries": "Sun Pharmaceutical Industries",
    ICICIBANK: "ICICIBANK",
    "ICICI Bank Ltd": "ICICI Bank Ltd",
    KOTAKBANK: "KOTAKBANK",
    "Kotak Mahindra Bank": "Kotak Mahindra Bank",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%",
    
    // Additional Layout UI elements
    wealth_intelligence: "Your wealth intelligence overview.",
    total: "TOTAL",
    housing_equity: "Housing & Equity",
    lifestyle_tech: "Lifestyle & Tech",
    risk_management_cat: "Risk Management",
    other: "Other"
  },
  hi: {
    action_blocked: "आपकी सुरक्षा के लिए कार्रवाई अवरुद्ध",
    security_review: "सुरक्षा समीक्षा आवश्यक है",
    action_approved: "लेनदेन स्वीकृत",
    confirm_after_review: "समीक्षा के बाद पुष्टि करें",
    cancel_action: "कार्रवाई रद्द करें",
    fraud_warning_title: "धोखाधड़ी चेतावनी",
    helpline_message: "अपने बैंक हेल्पलाइन से संपर्क करें",
    cooling_off_message: "कूलिंग-ऑफ अवधि सक्रिय",
    proceed: "आगे बढ़ें",
    blocked: "कार्रवाई अवरुद्ध",
    warning: "सावधानी आवश्यक",
    safe: "सुरक्षित कार्रवाई",
    close_logout: "बंद करें और लॉगआउट करें",
    wait: "प्रतीक्षा करें",
    proceed_anyway: "फिर भी आगे बढ़ें",
    high_risk: "उच्च धोखाधड़ी संभावना पकड़ी गई",
    elevated_risk: "उन्नत जोखिम",
    low_risk: "कम जोखिम",
    security_intercept: "सुरक्षा अवरोध",
    account_restricted: "अनधिकृत लेनदेन को रोकने के लिए आपका खाता अस्थायी रूप से प्रतिबंधित किया गया है।",
    
    // Core Layout
    dashboard: "डैशबोर्ड",
    goals: "लक्ष्य",
    netWorth: "कुल संपत्ति",
    net_worth: "कुल संपत्ति",
    portfolio: "पोर्टफोलियो",
    alertsRisk: "अलर्ट और जोखिम",
    alerts_risk: "अलर्ट और जोखिम",
    savings: "बचत",
    trending: "ट्रेंडिंग",
    inPortfolio: "पोर्टफोलियो में",
    in_portfolio: "पोर्टफोलियो में",
    bullish: "तेजी",
    bearish: "मंदी",
    neutral: "तटस्थ",
    allow: "स्वीकृत",
    warn: "चेतावनी",
    block: "अवरुद्ध",
    healthScore: "स्वास्थ्य स्कोर",
    health_score: "स्वास्थ्य स्कोर",
    marketNews: "बाजार समाचार",
    market_news: "बाजार समाचार",
    capitalOutflow: "पूंजी प्रवाह",
    capital_outflow: "पूंजी प्रवाह",
    savingsVelocity: "बचत वेग",
    savings_velocity: "बचत वेग",
    trending_stocks: "ट्रेंडिंग स्टॉक्स",
    cumulative_growth: "संचयी वृद्धि",
    allocation_priority: "आवंटन प्राथमिकता",
    growthTrajectory: "विकास पथ",
    growth_trajectory: "विकास पथ",
    coreHoldings: "मुख्य होल्डिंग्स",
    portfolioStrategy: "पोर्टफोलियो रणनीति",
    executerebalance: "पुनर्संतुलन निष्पादित करें",
    exportLedger: "लेज़र निर्यात करें",
    intelligenceReport: "इंटेलिजेंस रिपोर्ट",
    darkMode: "डार्क मोड",
    language: "भाषा",

    // Stocks
    RELIANCE: "रिलायंस",
    "Reliance Industries": "रिलायंस इंडस्ट्रीज",
    GOLDBEES: "गोल्डबीज",
    "Nippon India Gold BeES ETF": "निप्पॉन इंडिया गोल्ड बीज ईटीएफ",
    "Gold BeES ETF": "गोल्ड बीज ईटीएफ",
    HDFCBANK: "एचडीएफसी बैंक",
    "HDFC Bank Ltd": "एचडीएफसी बैंक लिमिटेड",
    TCS: "टीसीएस",
    "Tata Consultancy Services": "टाटा कंसल्टेंसी सर्विसेज",
    INFY: "इन्फोसिस",
    "Infosys Ltd": "इन्फोसिस लिमिटेड",
    SUNPHARMA: "सन फार्मा",
    "Sun Pharmaceutical Industries": "सन फार्मास्युटिकल इंडस्ट्रीज",
    ICICIBANK: "आईसीआईसीआई बैंक",
    "ICICI Bank Ltd": "आईसीआईसीआई बैंक लिमिटेड",
    KOTAKBANK: "कोटक बैंक",
    "Kotak Mahindra Bank": "कोटक महिंद्रा बैंक",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "आरबीआई ने लगातार छठी बैठक में रेपो दर को 6.5% पर बरकरार रखा — एफडी दरें आकर्षक बनी हुई हैं",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "सोने में इस वर्ष 13.7% की तेजी — सेबी ने खुदरा निवेशकों को लीवरेज्ड गोल्ड ईटीएफ खरीदने पर आगाह किया",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "एफआईआई की निकासी के बीच निफ्टी 50 में इस वर्ष 3.2% की गिरावट — एसआईपी निवेशकों को बने रहने की सलाह",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "सीपीआई मुद्रास्फीति बढ़कर 6.8% हुई — लगातार तीसरे महीने आरबीआई के संतोषजनक दायरे से ऊपर",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "सेबी ने शीर्ष 50 शेयरों के लिए नए टी+0 सेटलमेंट को मंजूरी दी — निवेशकों के लिए तेजी से फंड की उपलब्धता",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "एसबीआई ने 5-वर्षीय एफडी दर बढ़ाकर 7.75% की — सरकारी बैंकों में सबसे अधिक; एचडीएफसी बैंक 7.70% पर",

    wealth_intelligence: "आपकी संपत्ति बुद्धिमत्ता का अवलोकन।",
    total: "कुल",
    housing_equity: "आवास और इक्विटी",
    lifestyle_tech: "जीवनशैली और तकनीक",
    risk_management_cat: "जोखिम प्रबंधन",
    other: "अन्य"
  },
  ta: {
    action_blocked: "உங்கள் பாதுகாப்பிற்காக செயல் தடுக்கப்பட்டது",
    security_review: "பாதுகாப்பு மதிப்பாய்வு தேவை",
    action_approved: "பரிவர்த்தனை அங்கீகரிக்கப்பட்டது",
    confirm_after_review: "மதிப்பாய்வுக்குப் பிறகு உறுதிப்படுத்தவும்",
    cancel_action: "செயலை ரத்துசெய்",
    fraud_warning_title: "மோசடி எச்சரிக்கை",
    helpline_message: "உங்கள் வங்கி உதவி எண்ணை தொடர்பு கொள்ளவும்",
    cooling_off_message: "குளிர்விக்கும் காலம் செயல்படுகிறது",
    proceed: "தொடர்க",
    blocked: "செயல் தடுக்கப்பட்டது",
    warning: "எச்சரிக்கை தேவை",
    safe: "பாதுகாப்பான செயல்",
    close_logout: "மூடு மற்றும் வெளியேறு",
    wait: "காத்திரு",
    proceed_anyway: "எப்படியும் தொடர்க",
    high_risk: "அதிக மோசடி நிகழ்தகவு கண்டறியப்பட்டது",
    elevated_risk: "உயர் ஆபத்து",
    low_risk: "குறைந்த ஆபத்து",
    security_intercept: "பாதுகாப்பு தடையீடு",
    account_restricted: "அங்கீகரிக்கப்படாத நிதி நகர்வைத் தடுக்க உங்கள் கணக்கு தற்காலிகமாக தடைசெய்யப்பட்டுள்ளது.",
    
    // Core Layout
    dashboard: "டாஷ்போர்டு",
    goals: "இலக்குகள்",
    netWorth: "நிகர மதிப்பு",
    net_worth: "நிகர மதிப்பு",
    portfolio: "போர்ட்ஃபோலியோ",
    alertsRisk: "எச்சரிக்கைகள் & அபாயங்கள்",
    alerts_risk: "எச்சரிக்கைகள் & அபாயங்கள்",
    savings: "சேமிப்பு",
    trending: "பிரபலமானவை",
    inPortfolio: "போர்ட்ஃபோலியோவில்",
    in_portfolio: "போர்ட்ஃபோலியோவில்",
    bullish: "ஏற்றம்",
    bearish: "இறக்கம்",
    neutral: "நடுநிலை",
    allow: "அனுமதி",
    warn: "எச்சரிக்கை",
    block: "தடுப்பு",
    healthScore: "சுகாதார மதிப்பெண்",
    health_score: "சுகாதார மதிப்பெண்",
    marketNews: "சந்தை செய்திகள்",
    market_news: "சந்தை செய்திகள்",
    capitalOutflow: "மூலதன வெளியேற்றம்",
    capital_outflow: "மூலதன வெளியேற்றம்",
    savingsVelocity: "சேமிப்பு வேகம்",
    savings_velocity: "சேமிப்பு வேகம்",
    trending_stocks: "அதிகம் வர்த்தகமான பங்குகள்",
    cumulative_growth: "ஒட்டுமொத்த வளர்ச்சி",
    allocation_priority: "ஒதுக்கீட்டு முன்னுரிமை",
    growthTrajectory: "வளர்ச்சிப் பாதை",
    growth_trajectory: "வளர்ச்சிப் பாதை",
    coreHoldings: "முக்கிய பங்குகள்",
    portfolioStrategy: "போர்ட்ஃபோலியோ உத்தி",
    executerebalance: "மறுசீரமைப்பைச் செய்",
    exportLedger: "லெட்ஜரை ஏற்றுமதி செய்",
    intelligenceReport: "நுண்ணறிவு அறிக்கை",
    darkMode: "இருண்ட பயன்முறை",
    language: "மொழி",

    // Stocks
    RELIANCE: "ரிலையன்ஸ்",
    "Reliance Industries": "ரிலையன்ஸ் இண்டஸ்ட்ரீஸ்",
    GOLDBEES: "கோல்ட்பீஸ்",
    "Nippon India Gold BeES ETF": "நிப்பான் இந்தியா கோல்ட் பீஸ் இடிஎஃப்",
    "Gold BeES ETF": "கோல்ட் பீஸ் இடிஎஃப்",
    HDFCBANK: "எச்டிஎப்சி வங்கி",
    "HDFC Bank Ltd": "எச்டிஎப்சி வங்கி லிமிடெட்",
    TCS: "டிசிஎஸ்",
    "Tata Consultancy Services": "டாடா கன்சல்டன்சி சர்வீசஸ்",
    INFY: "இன்போசிஸ்",
    "Infosys Ltd": "இன்போசிஸ் லிமிடெட்",
    SUNPHARMA: "சன் பார்மா",
    "Sun Pharmaceutical Industries": "சன் பார்மாசூட்டிகல் இண்டஸ்ட்ரீஸ்",
    ICICIBANK: "ஐசிஐசிஐ வங்கி",
    "ICICI Bank Ltd": "ஐசிஐசிஐ வங்கி லிமிடெட்",
    KOTAKBANK: "கோடக் வங்கி",
    "Kotak Mahindra Bank": "கோடக் மஹிந்திரா வங்கி",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "ரிசர்வ் வங்கி வட்டி விகிதத்தை 6.5% ஆக மாற்றாமல் வைத்துள்ளது — எப்டி வட்டி விகிதங்கள் ஈர்க்கக்கூடியதாக உள்ளன",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "தங்கம் இந்த ஆண்டில் 13.7% உயர்வு — கோல்ட் இடிஎஃப் வாங்குவதில் சில்லறை முதலீட்டாளர்களை செபி எச்சரிக்கிறது",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "நிஃப்டி 50 இந்த ஆண்டில் 3.2% சரிவு — எஸ்ஐபி முதலீட்டாளர்கள் தொடர்ந்து முதலீடு செய்ய அறிவுறுத்தப்படுகிறார்கள்",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "நுகர்வோர் விலை பணவீக்கம் 6.8% ஆக உயர்வு — தொடர்ந்து மூன்றாவது மாதமாக ரிசர்வ் வங்கியின் இலக்கை விட அதிகம்",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "செபி டாப் 50 பங்குகளுக்கு புதிய டி+0 செட்டில்மெண்டிற்கு ஒப்புதல் அளித்துள்ளது — முதலீட்டாளர்களுக்கு விரைவான பணப் புழக்கம்",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "எஸ்பிஐ 5 ஆண்டு எப்டி வட்டி விகிதத்தை 7.75% ஆக உயர்த்தியது — பொதுத்துறை வங்கிகளில் மிக அதிகம்; எச்டிஎப்சி 7.70% ஆக வழங்குகிறது",

    wealth_intelligence: "உங்கள் செல்வ நுண்ணறிவு கண்ணோட்டம்.",
    total: "மொத்தம்",
    housing_equity: "வீட்டுவசதி & ஈக்விட்டி",
    lifestyle_tech: "வாழ்க்கை முறை & தொழில்நுட்பம்",
    risk_management_cat: "அபாய மேலாண்மை",
    other: "மற்றவை"
  },
  te: {
    action_blocked: "మీ రక్షణ కోసం చర్య నిరోధించబడింది",
    security_review: "భద్రతా సమీక్ష అవసరం",
    action_approved: "లావాదేవీ ఆమోదించబడింది",
    confirm_after_review: "సమీక్ష తర్వాత నిర్ధారించండి",
    cancel_action: "చర్యను రద్దు చేయి",
    fraud_warning_title: "మోసం హెచ్చరిక",
    helpline_message: "మీ బ్యాంక్ హెల్ప్‌లైన్‌ని సంప్రదించండి",
    cooling_off_message: "కూలింగ్-ఆఫ్ వ్యవధి సక్రియంగా ఉంది",
    proceed: "కొనసాగించు",
    blocked: "చర్య నిరోధించబడింది",
    warning: "జాగ్రత్త అవసరం",
    safe: "సురక్షిత చర్య",
    close_logout: "మూసి లాగ్అవుట్ చేయి",
    wait: "వేచి ఉండు",
    proceed_anyway: "అయినా కొనసాగించు",
    high_risk: "ఆరోపించిన మోసం పరిమితి మించినది",
    elevated_risk: "పెరిగిన ప్రమాదం",
    low_risk: "తక్కువ ప్రమాదం",
    security_intercept: "భద్రతా అడ్డగింత",
    account_restricted: "అనధికార నిధుల చలనాన్ని నిరోధించడానికి మీ ఖాతా తాత్కాలికంగా నిరోధించబడింది.",
    
    // Core Layout
    dashboard: "డాష్‌బోర్డ్",
    goals: "లక్ష్యాలు",
    netWorth: "निకర నిల్వలు",
    net_worth: "నికర విలువ",
    portfolio: "పోర్ట్‌ఫోలియో",
    alertsRisk: "హెచ్చరికలు & ప్రమాదాలు",
    alerts_risk: "హెచ్చరికలు & ప్రమాదాలు",
    savings: "పొదుపు",
    trending: "ట్రెండింగ్",
    inPortfolio: "పోర్ట్‌ఫోలియోలో",
    in_portfolio: "పోర్ట్‌ఫోలియోలో",
    bullish: "తేజీ",
    bearish: "మందగమనం",
    neutral: "తటస్థ",
    allow: "అనుమతించు",
    warn: "హెచ్చరిక",
    block: "బ్లాక్ చేయి",
    healthScore: "ఆరోగ్య స్కోరు",
    health_score: "ఆరోగ్య స్కోరు",
    marketNews: "మార్కెట్ వార్తలు",
    market_news: "మార్కెట్ వార్తలు",
    capitalOutflow: "మూలధన ప్రవాహం",
    capital_outflow: "మూలధన ప్రవాహం",
    savingsVelocity: "పొదుపు వేగం",
    savings_velocity: "పొదుపు వేగం",
    trending_stocks: "ట్రెండింగ్ స్టాక్‌లు",
    cumulative_growth: "సంచిత వృద్ధి",
    allocation_priority: "కేటాయింపు ప్రాధాన్యత",
    growthTrajectory: "వృద్ధి పథం",
    growth_trajectory: "వృద్ధి పథం",
    coreHoldings: "కోర్ హోల్డింగ్స్",
    portfolioStrategy: "పోర్ట్‌ఫోలియో వ్యూహం",
    executerebalance: "రీబ్యాలెన్స్ చేయి",
    exportLedger: "లెడ్జర్‌ను ఎగుమతి చేయి",
    intelligenceReport: "ఇంటెలిజెన్స్ నివేదిక",
    darkMode: "డార్క్ మోడ్",
    language: "భాష",

    // Stocks
    RELIANCE: "రిలయన్స్",
    "Reliance Industries": "రిలయన్స్ ఇండస్ట్రీస్",
    GOLDBEES: "గోల్డ్‌బీస్",
    "Nippon India Gold BeES ETF": "నిప్పాన్ ఇండియా గోల్డ్ బీస్ ఈటిఎఫ్",
    "Gold BeES ETF": "గోల్డ్ బీస్ ఈటిఎఫ్",
    HDFCBANK: "హెచ్‌డిఎఫ్‌సి బ్యాంక్",
    "HDFC Bank Ltd": "హెచ్‌డిఎఫ్‌సి బ్యాంక్ లిమిటెడ్",
    TCS: "టిసిఎస్",
    "Tata Consultancy Services": "టాటా కన్సల్టెన్సీ సర్వీసెస్",
    INFY: "ఇన్ఫోసిస్",
    "Infosys Ltd": "ఇన్ఫోసిస్ లిమిటెడ్",
    SUNPHARMA: "సన్ ఫార్మా",
    "Sun Pharmaceutical Industries": "సన్ ఫార్మాస్యూటికల్ ఇండస్ట్రీస్",
    ICICIBANK: "ఐసిఐసిఐ బ్యాంక్",
    "ICICI Bank Ltd": "ఐసిఐసిఐ బ్యాంక్ లిమిటెడ్",
    KOTAKBANK: "కోటక్ బ్యాంక్",
    "Kotak Mahindra Bank": "కోటక్ మహీంద్రా బ్యాంక్",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "ఆర్బీఐ రెపో రేటును 6.5% వద్ద స్థిరంగా ఉంచింది — ఎఫ్‌డీ రేట్లు ఆకర్షణీయంగా ఉన్నాయి",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "బంగారం ఈ ఏడాది 13.7% పెరిగింది — రిటైల్ ఇన్వెస్టర్లను హెచ్చరించిన సెబీ",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "నిఫ్టీ 50 ఈ ఏడాది 3.2% పడిపోయింది — ఎస్ఐపీ ఇన్వెస్టర్లకు కొనసాగాలని సలహా",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "సీపీఐ ద్రవ్యోల్బణం 6.8%కి పెరిగింది — వరుసగా మూడో నెల ఆర్బీఐ పరిమితి కంటే ఎక్కువ",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "టాప్ 50 స్టాక్స్‌కు కొత్త టీ+0 సెటిల్‌మెంట్‌ను ఆమోదించిన సెబీ — ఇన్వెస్టర్లకు వేగంగా నిధుల లభ్యత",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "ఎస్‌బీఐ 5 ఏళ్ల ఎఫ్‌డీ రేటును 7.75%కి పెంచింది — పీఎస్‌బీలలో అత్యధికం; హెచ్‌డీఎఫ్‌సీ 7.70% వద్ద సరిపోలింది",

    wealth_intelligence: "మీ సంపద మేధస్సు అవలోకనం.",
    total: "మొత్తం",
    housing_equity: "గృహనిర్మాణం & ఈక్విటీ",
    lifestyle_tech: "జీవనశైలి & టెక్నాలజీ",
    risk_management_cat: "రిస్క్ మేనేజ్‌మెంట్",
    other: "ఇతర"
  },
  bn: {
    action_blocked: "আপনার সুরক্ষার জন্য কার্যক্রম অবরুদ্ধ",
    security_review: "নিরাপত্তা পর্যালোচনা প্রয়োজন",
    action_approved: "লেনদেন অনুমোদিত",
    confirm_after_review: "পর্যালোচনার পরে নিশ্চিত করুন",
    cancel_action: "কার্যক্রম বাতিল করুন",
    fraud_warning_title: "জালিয়াতি সতর্কতা",
    helpline_message: "আপনার ব্যাংক হেল্পলাইনে যোগাযোগ করুন",
    cooling_off_message: "কুলিং-অফ পিরিয়ড সক্রিয়",
    proceed: "এগিয়ে যান",
    blocked: "কার্যক্রম অবরুদ্ধ",
    warning: "সতর্কতা প্রয়োজন",
    safe: "নিরাপদ কার্যক্রম",
    close_logout: "বন্ধ করুন এবং লগআউট করুন",
    wait: "অপেক্ষা করুন",
    proceed_anyway: "যাইহোক এগিয়ে যান",
    high_risk: "উচ্চ জালিয়াতির সম্ভাবনা সনাক্ত হয়েছে",
    elevated_risk: "উন্নত ঝুঁকি",
    low_risk: "কম ঝুঁকি",
    security_intercept: "নিরাপত্তা বাধা",
    account_restricted: "অননুমোদিত তহবিল স্থানান্তর রোধ করতে আপনার অ্যাকাউন্ট সাময়িকভাবে সীমাবদ্ধ করা হয়েছে।",
    
    // Core Layout
    dashboard: "ড্যাশবোর্ড",
    goals: "লক্ষ্যসমূহ",
    netWorth: "মোট সম্পদ",
    net_worth: "মোট সম্পদ",
    portfolio: "পোর্টফোলিও",
    alertsRisk: "সতর্কতা এবং ঝুঁকি",
    alerts_risk: "সতর্কতা এবং ঝুঁকি",
    savings: "সঞ্চয়",
    trending: "ট্রেন্ডিং",
    inPortfolio: "পোর্টফোলিওতে",
    in_portfolio: "পোর্টফোলিওতে",
    bullish: "তেজি",
    bearish: "মন্দা",
    neutral: "নিরপেক্ষ",
    allow: "অনুমোদিত",
    warn: "সতর্কীকরণ",
    block: "অবরুদ্ধ",
    healthScore: "স্বাস্থ্য স্কোর",
    health_score: "স্বাস্থ্য স্কোর",
    marketNews: "বাজারের খবর",
    market_news: "বাজারের খবর",
    capitalOutflow: "মূলধন বহিঃপ্রবাহ",
    capital_outflow: "মূলধন বহিঃপ্রবাহ",
    savingsVelocity: "সঞ্চয় গতি",
    savings_velocity: "সঞ্চয় গতি",
    trending_stocks: "ট্রেন্ডিং স্টক",
    cumulative_growth: "ক্রমবর্ধমান বৃদ্ধি",
    allocation_priority: "বরাদ্দ অগ্রাধিকার",
    growthTrajectory: "প্রবৃদ্ধির গতিপথ",
    growth_trajectory: "প্রবৃদ্ধির গতিপথ",
    coreHoldings: "মূল হোল্ডিংস",
    portfolioStrategy: "পোর্টফোলিও কৌশল",
    executerebalance: "পুনঃভারসাম্য করুন",
    exportLedger: "লেজার রপ্তানি করুন",
    intelligenceReport: "গোয়েন্দা প্রতিবেদন",
    darkMode: "ডার্ক মোড",
    language: "ভাষা",

    // Stocks
    RELIANCE: "রিল্যায়েন্স",
    "Reliance Industries": "রিলায়েন্স ইন্ডাস্ট্রিজ",
    GOLDBEES: "গোল্ডবিজ",
    "Nippon India Gold BeES ETF": "নিপ্পন ইন্ডিয়া গোল্ড বিইএস ইটিএফ",
    "Gold BeES ETF": "গোল্ড বিইএস ইটিএফ",
    HDFCBANK: "এইচডিএফসি ব্যাংক",
    "HDFC Bank Ltd": "এইচডিএফসি ব্যাংক লিমিটেড",
    TCS: "টিসিএস",
    "Tata Consultancy Services": "টাটা কনসালটেন্সি সার্ভিসেস",
    INFY: "ইনফোসিস",
    "Infosys Ltd": "ইনফোসিস লিমিটেড",
    SUNPHARMA: "সান ফার্মা",
    "Sun Pharmaceutical Industries": "সান ফার্মাসিউটিক্যাল ইন্ডাস্ট্রিজ",
    ICICIBANK: "আইসিআইসিআই ব্যাংক",
    "ICICI Bank Ltd": "আইসিআইসিআই ব্যাংক লিমিটেড",
    KOTAKBANK: "কোটাক ব্যাংক",
    "Kotak Mahindra Bank": "কোটাক মাহিন্দ্রা ব্যাংক",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "আরবিআই রেপো রেট ৬.৫%-এ অপরিবর্তিত রেখেছে — এফডি রেট আকর্ষনীয় রয়েছে",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "সোনার মূল্য ১৩.৭% বৃদ্ধি পেয়েছে — ইটিএফ ক্রয়ে সেবির সতর্কতা জারি",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "বিদেশী তহবিল প্রত্যাহারের জেরে নিফটি ৩.২% হ্রাস — এসআইপি বিনিয়োগকারীদের ধরে রাখার পরামর্শ",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "সিপিআই মূল্যস্ফীতি বেড়ে ৬.৮% হয়েছে — টানা তৃতীয় মাসের জন্য আরবিআই সীমার উপরে",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "সেবি শীর্ষ ৫০ স্টকের জন্য নতুন টি+০ সেটেলমেন্ট অনুমোদন করেছে — দ্রুত তহবিল প্রাপ্তি",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "এসবিআই ৫ বছরের এফডি সুদের হার বাড়িয়ে ৭.৭৫% করেছে; এইচডিএফসি ব্যাংকের সুদের হার ৭.৭০%",

    wealth_intelligence: "আপনার সম্পদ বুদ্ধিমত্তার সংক্ষিপ্ত বিবরণ।",
    total: "মোট",
    housing_equity: "গৃহায়ন ও ইকুইটি",
    lifestyle_tech: "লাইফস্টাইল ও টেক",
    risk_management_cat: "ঝুঁকি ব্যবস্থাপনা",
    other: "অন্যান্য"
  },
  mr: {
    action_blocked: "तुमच्या संरक्षणासाठी कृती अवरोधित",
    security_review: "सुरक्षा पुनरावलोकन आवश्यक",
    action_approved: "व्यवहार मंजूर",
    confirm_after_review: "पुनरावलोकनानंतर पुष्टी करा",
    cancel_action: "कृती रद्द करा",
    fraud_warning_title: "फसवणूक इशारा",
    helpline_message: "तुमच्या बँक हेल्पलाइनशी संपर्क करा",
    cooling_off_message: "कूलिंग-ऑफ कालावधी सक्रिय",
    proceed: "पुढे जा",
    blocked: "कृती अवरोधित",
    warning: "सावधगिरी आवश्यक",
    safe: "सुरक्षित कृती",
    close_logout: "बंद करा आणि लॉगआउट करा",
    wait: "थांबा",
    proceed_anyway: "तरीही पुढे जा",
    high_risk: "उच्च फसवणुकीची शक्यता आढळली",
    elevated_risk: "वाढलेला धोका",
    low_risk: "कमी धोका",
    security_intercept: "सुरक्षा अवरोध",
    account_restricted: "अनधिकृत निधी हस्तांतरण रोखण्यासाठी तुमचे खाते तात्पुरते प्रतिबंधित केले आहे.",
    
    // Core Layout
    dashboard: "डॅशबोर्ड",
    goals: "ध्येय",
    netWorth: "निव्वळ मालमत्ता",
    net_worth: "निव्वळ मालमत्ता",
    portfolio: "पोर्टफोलिओ",
    alertsRisk: "अलर्ट आणि जोखीम",
    alerts_risk: "अलर्ट आणि जोखीम",
    savings: "बचत",
    trending: "ट्रेंडिंग",
    inPortfolio: "पोर्टफोलिओमध्ये",
    in_portfolio: "पोर्टफोलिओमध्ये",
    bullish: "तेजी",
    bearish: "मंदी",
    neutral: "तटस्थ",
    allow: "मंजूर",
    warn: "इशारा",
    block: "अवरोधित",
    healthScore: "आरोग्य स्कोअर",
    health_score: "आरोग्य स्कोअर",
    marketNews: "बाजार बातम्या",
    market_news: "बाजार बातम्या",
    capitalOutflow: "भांडवली प्रवाह",
    capital_outflow: "भांडवली प्रवाह",
    savingsVelocity: "बचत वेग",
    savings_velocity: "बचत वेग",
    trending_stocks: "ट्रेंडिंग स्टॉक्स",
    cumulative_growth: "एकत्रित वाढ",
    allocation_priority: "वाटप प्राधान्य",
    growthTrajectory: "विकास मार्ग",
    growth_trajectory: "विकास मार्ग",
    coreHoldings: "मुख्य होल्डिंग्ज",
    portfolioStrategy: "पोर्टफोलिओ धोरण",
    executerebalance: "रीबॅलन्स करा",
    exportLedger: "लेजर निर्यात करा",
    intelligenceReport: "इंटेलिजेंस रिपोर्ट",
    darkMode: "डार्क मोड",
    language: "भाषा",

    // Stocks
    RELIANCE: "रिलायन्स",
    "Reliance Industries": "रिलायन्स इंडस्ट्रीज",
    GOLDBEES: "गोल्डबीज",
    "Nippon India Gold BeES ETF": "निप्पॉन इंडिया गोल्ड बीज ईटीएफ",
    "Gold BeES ETF": "गोल्ड बीज ईटीएफ",
    HDFCBANK: "एचडीएफसी बँक",
    "HDFC Bank Ltd": "एचडीएफसी बँक लिमिटेड",
    TCS: "टीसीएस",
    "Tata Consultancy Services": "टाटा कन्सल्टन्सी सर्व्हिसेस",
    INFY: "इन्फोसिस",
    "Infosys Ltd": "इन्फोसिस लिमिटेड",
    SUNPHARMA: "सन फार्मा",
    "Sun Pharmaceutical Industries": "सन फार्मास्युटिकल इंडस्ट्रीज",
    ICICIBANK: "आयसीआयसीआय बँक",
    "ICICI Bank Ltd": "आयसीआयसीआय बँक लिमिटेड",
    KOTAKBANK: "कोटक बँक",
    "Kotak Mahindra Bank": "कोटक महिंद्रा बँक",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "आरबीआयने रेपो दर ६.५% वर कायम ठेवला — एफडीचे व्याजदर आकर्षक राहिले",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "सोन्यामध्ये १३.७% वाढ — सेबीकडून गुंतवणूकदारांना सावधगिरीचा इशारा",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "परदेशी गुंतवणुकीच्या बाहेर पडल्याने निफ्टी ३.२% घसरला — एसआयपी गुंतवणूकदारांना टिकून राहण्याचा सल्ला",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "सीपीआय महागाई ६.८% वर पोहोचली — सलग तिसऱ्या महिन्यात आरबीआयच्या लक्ष्यापेक्षा जास्त",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "सेबीने टॉप ५० शेअर्ससाठी नवीन टी+० सेटलमेंट मंजूर केले — वेगवान निधी उपलब्धता",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "एसबीआयने ५ वर्षांच्या एफडीचे व्याजदर ७.७५% केले; एचडीएफसी बँक ७.७०% व्याजदर देईल",

    wealth_intelligence: "तुमचा संपत्ती बुद्धिमत्ता आढावा.",
    total: "एकूण",
    housing_equity: "गृहनिर्माण आणि इक्विटी",
    lifestyle_tech: "जीवनशैली आणि तंत्रज्ञान",
    risk_management_cat: "जोखिम व्यवस्थापन",
    other: "इतर"
  },
  kn: {
    action_blocked: "ನಿಮ್ಮ ರಕ್ಷಣೆಗಾಗಿ ಕ್ರಿಯೆಯನ್ನು ತಡೆಯಲಾಗಿದೆ",
    security_review: "ಭದ್ರತಾ ಪರಿಶೀಲನೆ ಅಗತ್ಯ",
    action_approved: "ವ್ಯವಹಾರ ಅನುಮೋದಿಸಲಾಗಿದೆ",
    confirm_after_review: "ಪರಿಶೀಲನೆ ನಂತರ ದೃಢೀಕರಿಸಿ",
    cancel_action: "ಕ್ರಿಯೆ ರದ್ದುಗೊಳಿಸಿ",
    fraud_warning_title: "ಮೋಸದ ಎಚ್ಚರಿಕೆ",
    helpline_message: "ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಸಹಾಯವಾಣಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ",
    cooling_off_message: "ತಣಿಸುವ ಅವಧಿ ಸಕ್ರಿಯ",
    proceed: "ಮುಂದುವರಿಸಿ",
    blocked: "ಕ್ರಿಯೆ ತಡೆಯಲಾಗಿದೆ",
    warning: "ಎಚ್ಚರಿಕೆ ಅಗತ್ಯ",
    safe: "ಸುರಕ್ಷಿತ ಕ್ರಿಯೆ",
    close_logout: "ಮುಚ್ಚಿ ಮತ್ತು ಲಾಗ್‌ಔಟ್ ಮಾಡಿ",
    wait: "ನಿರೀಕ್ಷಿಸಿ",
    proceed_anyway: "ಹೇಗಾದರೂ ಮುಂದುವರಿಸಿ",
    high_risk: "ಹೆಚ್ಚಿನ ಮೋಸದ ಸಂಭಾವ್ಯತೆ ಪತ್ತೆಯಾಗಿದೆ",
    elevated_risk: "ಹೆಚ್ಚಿದ ಅಪಾಯ",
    low_risk: "ಕಡಿಮೆ ಅಪಾಯ",
    security_intercept: "ಭದ್ರತಾ ಅಡ್ಡಿ",
    account_restricted: "ಅನಧಿಕೃತ ನಿಧಿ ಚಲನೆಯನ್ನು ತಡೆಯಲು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ತಾತ್ಕಾಲಿಕವಾಗಿ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ.",
    
    // Core Layout
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    goals: "ಗುರಿಗಳು",
    netWorth: "ನಿವ್ವಳ ಮೌಲ್ಯ",
    net_worth: "ನಿವ್ವಳ ಮೌಲ್ಯ",
    portfolio: "ಪೋರ್ಟ್‌ಫೋಲಿಯೋ",
    alertsRisk: "ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಅಪಾಯಗಳು",
    alerts_risk: "ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಅಪಾಯಗಳು",
    savings: "ಉಳಿತಾಯ",
    trending: "ಟ್ರೆಂಡಿಂಗ್",
    inPortfolio: "ಪೋರ್ಟ್‌ಫೋಲಿಯೊದಲ್ಲಿದೆ",
    in_portfolio: "ಪೋರ್ಟ್‌ಫೋಲಿಯೊದಲ್ಲಿದೆ",
    bullish: "ತೇಜಿ",
    bearish: "ಮಂದಗತಿ",
    neutral: "ತಟಸ್ಥ",
    allow: "ಅನುಮತಿಸು",
    warn: "ಎಚ್ಚರಿಕೆ",
    block: "ಬ್ಲಾಕ್ ಮಾಡು",
    healthScore: "ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    health_score: "ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    marketNews: "ಮಾರುಕಟ್ಟೆ ಸುದ್ದಿ",
    market_news: "ಮಾರುಕಟ್ಟೆ ಸುದ್ದಿ",
    capitalOutflow: "ಬಂಡವಾಳ ಹೊರಹರಿವು",
    capital_outflow: "ಬಂಡವಾಳ ಹೊರಹರಿವು",
    savingsVelocity: "ಉಳಿತಾಯ ವೇಗ",
    savings_velocity: "ಉಳಿತಾಯ ವೇಗ",
    trending_stocks: "ಟ್ರೆಂಡಿಂಗ್ ಷೇರುಗಳು",
    cumulative_growth: "ಸಂಚಿತ ಬೆಳವಣಿಗೆ",
    allocation_priority: "ಹಂಚಿಕೆ ಆದ್ಯತೆ",
    growthTrajectory: "ಬೆಳವಣಿಗೆಯ ಪಥ",
    growth_trajectory: "ಬೆಳವಣಿಗೆಯ ಪಥ",
    coreHoldings: "ಕೋರ್ ಹೋಲ್ಡಿಂಗ್ಸ್",
    portfolioStrategy: "ಪೋರ್ಟ್‌ಫೋಲಿಯೋ ತಂತ್ರ",
    executerebalance: "ಮರುಸಮತೋಲನಗೊಳಿಸು",
    exportLedger: "ಲೆಡ್ಜರ್ ರಫ್ತು ಮಾಡು",
    intelligenceReport: "ಬುದ್ಧಿವಂತಿಕೆ ವರದಿ",
    darkMode: "ಡಾರ್ಕ್ ಮೋಡ್",
    language: "ಭಾಷೆ",

    // Stocks
    RELIANCE: "ರಿಲಯನ್ಸ್",
    "Reliance Industries": "ರಿಲಯನ್ಸ್ ಇಂಡಸ್ಟ್ರೀಸ್",
    GOLDBEES: "ಗೋಲ್ಡ್‌ಬೀಸ್",
    "Nippon India Gold BeES ETF": "ನಿಪ್ಪಾನ್ ಇಂಡಿಯಾ ಗೋಲ್ಡ್ ಬೀಸ್ ಇಟಿಎಫ್",
    "Gold BeES ETF": "ಗೋಲ್ಡ್ ಬೀಸ್ ಇಟಿಎಫ್",
    HDFCBANK: "ಎಚ್‌ಡಿಎಫ್‌ಸಿ ಬ್ಯಾಂಕ್",
    "HDFC Bank Ltd": "ಎಚ್‌ಡಿಎಫ್‌ಸಿ ಬ್ಯಾಂಕ್ ಲಿಮಿಟೆಡ್",
    TCS: "ಟಿಸಿಎಸ್",
    "Tata Consultancy Services": "ಟಾಟಾ ಕನ್ಸಲ್ಟೆನ್ಸಿ ಸರ್ವೀಸಸ್",
    INFY: "ಇನ್ಫೋಸಿಸ್",
    "Infosys Ltd": "ಇನ್ಫೋಸಿಸ್ ಲಿಮಿಟೆಡ್",
    SUNPHARMA: "ಸನ್ ಫಾರ್ಮಾ",
    "Sun Pharmaceutical Industries": "ಸನ್ ಫಾರ್ಮಾಸ್ಯೂಟಿಕಲ್ ಇಂಡಸ್ಟ್ರೀಸ್",
    ICICIBANK: "ಐಸಿಐಸಿಐ ಬ್ಯಾಂಕ್",
    "ICICI Bank Ltd": "ಐಸಿಐಸಿಐ ಬ್ಯಾಂಕ್ ಲಿಮಿಟೆಡ್",
    KOTAKBANK: "ಕೋಟಕ್ ಬ್ಯಾಂಕ್",
    "Kotak Mahindra Bank": "ಕೋಟಕ್ ಮಹೀಂದ್ರಾ ಬ್ಯಾಂಕ್",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "ಆರ್‌ಬಿಐ ರೆಪೊ ದರವನ್ನು 6.5% ರಲ್ಲೇ ಮುಂದುವರೆಸಿದೆ — ಎಫ್‌ಡಿ ದರಗಳು ಆಕರ್ಷಕವಾಗಿವೆ",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "ಚಿನ್ನದ ಬೆಲೆ ಶೇ 13.7 ರಷ್ಟು ಏರಿಕೆ — ಹೂಡಿಕೆದಾರರಿಗೆ ಸೆಬಿ ಎಚ್ಚರಿಕೆ",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "ವಿದೇಶಿ ಬಂಡವಾಳ ಹಿಂತೆಗೆತದಿಂದ ನಿಫ್ಟಿ 50 ಶೇ 3.2 ಕುಸಿತ — ಎಸ್ಐಪಿ ಮುಂದುವರೆಸಲು ಹೂಡಿಕೆದಾರರಿಗೆ ಸಲಹೆ",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "ಗ್ರಾಹಕ ಬೆಲೆ ಹಣದುಬ್ಬರ ಶೇ 6.8 ಕ್ಕೆ ಏರಿಕೆ — ಸತತ ಮೂರನೇ ತಿಂಗಳಲ್ಲೂ ಆರ್‌ಬಿಐ ಮಿತಿ ಮೀರಿ ಹೆಚ್ಚಳ",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "ಟಾಪ್ 50 ಷೇರುಗಳಿಗೆ ಹೊಸ ಟಿ+0 ಸೆಟಲ್‌ಮೆಂಟ್‌ಗೆ ಸೆಬಿ ಅನುಮೋದನೆ — ತ್ವರಿತ ಹಣದ ಲಭ್ಯತೆ",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "ಎಸ್‌ಬಿಐ 5 ವರ್ಷದ ಎಫ್‌ಡಿ ದರವನ್ನು ಶೇ 7.75 ಕ್ಕೆ ಹೆಚ್ಚಿಸಿದೆ; ಎಚ್‌ಡಿಎಫ್‌ಸಿ ಬ್ಯಾಂಕ್ ಶೇ 7.70 ರಷ್ಟು ನೀಡಲಿದೆ",

    wealth_intelligence: "ನಿಮ್ಮ ಸಂಪತ್ತು ಬುದ್ಧಿವಂತಿಕೆಯ ಅವಲೋಕನ.",
    total: "ಒಟ್ಟು",
    housing_equity: "ವಸತಿ ಮತ್ತು ಇಕ್ವಿಟಿ",
    lifestyle_tech: "ಜೀವನಶೈಲಿ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ",
    risk_management_cat: "ಅಪಾಯ ನಿರ್ವಹಣೆ",
    other: "ಇತರ"
  },
  gu: {
    action_blocked: "તમારી સુરક્ષા માટે ક્રિયા અવરોધિત",
    security_review: "સુરક્ષા સમીક્ષા જરૂરી",
    action_approved: "વ્યવહાર મંજૂર",
    confirm_after_review: "સમીક્ષા પછી પુષ્ટિ કરો",
    cancel_action: "ક્રિયા રદ કરો",
    fraud_warning_title: "છેતરપિંડી ચેતવણી",
    helpline_message: "તમારી બેંક હેલ્પલાઇનનો સંપર્ક કરો",
    cooling_off_message: "કૂલિંગ-ઓફ સમયગાળો સક્રિય",
    proceed: "આગળ વધો",
    blocked: "ક્રિયા અવરોધિત",
    warning: "સાવધાની જરૂરી",
    safe: "સુરક્ષિત ક્રિયા",
    close_logout: "બંધ કરો અને લૉગઆઉટ કરો",
    wait: "રાહ જુઓ",
    proceed_anyway: "ગમે તો આગળ વધો",
    high_risk: "સમસ્યા સંભવિત છેતરપિંડી",
    elevated_risk: "વધેલ જોખમ",
    low_risk: "ઓછું જોખમ",
    security_intercept: "સુરક્ષા અવરોધ",
    account_restricted: "અનધિકૃત ભંડોળ ચળવળ અટકાવવા માટે તમારા ખાતાને અસ્થાયી રૂપે પ્રતિબંધિત કરવામાં આવ્યું છે.",
    
    // Core Layout
    dashboard: "ડેશબોર્ડ",
    goals: "લક્ષ્યો",
    netWorth: "ચોખ્ખી સંપત્તિ",
    net_worth: "ચોખ્ખી સંપત્તિ",
    portfolio: "પોર્ટફોલિયો",
    alertsRisk: "ચેતવણીઓ અને જોખમ",
    alerts_risk: "ચેતવણીઓ અને જોખમ",
    savings: "બચત",
    trending: "ટ્રેન્ડિંગ",
    inPortfolio: "પોર્ટફોલિયોમાં",
    in_portfolio: "પોર્ટફોલિયોમાં",
    bullish: "તેજી",
    bearish: "મંદી",
    neutral: "તટસ્થ",
    allow: "મંજૂર",
    warn: "ચેતવણી",
    block: "અવરોધિત",
    healthScore: "આરોગ્ય સ્કોર",
    health_score: "આરોગ્ય સ્કોર",
    marketNews: "બજાર સમાચાર",
    market_news: "બજાર સમાચાર",
    capitalOutflow: "મૂડી પ્રવાહ",
    capital_outflow: "મૂડી પ્રવાહ",
    savingsVelocity: "બચત વેગ",
    savings_velocity: "બચત વેગ",
    trending_stocks: "ટ્રેન્ડિંગ સ્ટોક્સ",
    cumulative_growth: "સંચિત વૃદ્ધિ",
    allocation_priority: "ફાળવણી પ્રાથમિકતા",
    growthTrajectory: "વિકાસ પથ",
    growth_trajectory: "વિકાસ પથ",
    coreHoldings: "મુખ્ય હોલ્ડિંગ્સ",
    portfolioStrategy: "પોર્ટફોલિયો વ્યૂહરચના",
    executerebalance: "રીબેલેન્સ કરો",
    exportLedger: "લેજર નિકાસ કરો",
    intelligenceReport: "ઇન્ટેલિજન્સ રિપોર્ટ",
    darkMode: "ડાર્ક મોડ",
    language: "ભાષા",

    // Stocks
    RELIANCE: "રિલાયન્સ",
    "Reliance Industries": "રિલાયન્સ ઇન્ડસ્ટ્રીઝ",
    GOLDBEES: "ગોલ્ડબીઝ",
    "Nippon India Gold BeES ETF": "નિપ્પોન ઇન્ડિયા ગોલ્ડ બીઝ ઇટીએફ",
    "Gold BeES ETF": "ગોલ્ડ બીઝ ઇટીએફ",
    HDFCBANK: "એચડીએફસી બેંક",
    "HDFC Bank Ltd": "એચડીએફસી બેંક લિમિટેડ",
    TCS: "ટીસીએસ",
    "Tata Consultancy Services": "ટાટા કન્સલ્ટન્સી સર્વિસીસ",
    INFY: "ઇન્ફોસીસ",
    "Infosys Ltd": "ઇન્ફોસીસ લિમિટેડ",
    SUNPHARMA: "સન ફાર્મા",
    "Sun Pharmaceutical Industries": "સન ફાર્માસ્યુટિકલ ઇન્ડસ્ટ્રીઝ",
    ICICIBANK: "આઈસીઆઈસીઆઈ બેંક",
    "ICICI Bank Ltd": "આઈસીઆઈસીઆઈ બેંક લિમિટેડ",
    KOTAKBANK: "કોટક બેંક",
    "Kotak Mahindra Bank": "કોટક મહિન્દ્રા બેંક",

    // Headlines
    "RBI holds repo rate at 6.5% for sixth consecutive meeting — FD rates remain attractive": "આરબીઆઈએ સતત છઠ્ઠી બેઠકમાં રેપો રેટ 6.5% પર જાળવી રાખ્યો — એફડી દરો આકર્ષક રહ્યા",
    "Gold surges 13.7% YTD — SEBI cautions retail investors on leveraged gold ETF buying": "સોનામાં ચાલુ વર્ષે 13.7% નો ઉછાળો — સેબીએ રિટેલ રોકાણકારોને સાવધ કર્યા",
    "Nifty 50 slips 3.2% YTD amid FII outflows — SIP investors advised to stay the course": "એફઆઈઆઈ નિકાસ વચ્ચે નિફ્ટી 50 માં 3.2% નો ઘટાડો — એસઆઈપી ચાલુ રાખવા સલાહ",
    "CPI inflation rises to 6.8% — above RBI comfort band for third consecutive month": "સીપીઆઈ ફુગાવો વધીને 6.8% થયો — સતત ત્રીજા મહિને આરબીઆઈ લક્ષ્યથી ઉપર",
    "SEBI approves new T+0 settlement for top 50 stocks — faster fund availability for investors": "સેબીએ ટોપ 50 સ્ટોક્સ માટે નવું ટી+0 સેટલમેન્ટ મંજૂર કર્યું — રોકાણકારો માટે ઝડપી ભંડોળ",
    "SBI raises 5-year FD rate to 7.75% — highest among PSBs; HDFC Bank matches at 7.70%": "એસબીઆઈએ 5 વર્ષની એફડી દર વધારી 7.75% કર્યો; એચડીએફસી બેંક 7.70% આપશે",

    wealth_intelligence: "તમારી સંપત્તિ બુદ્ધિની ઝાંખી.",
    total: "કુલ",
    housing_equity: "આવાસ અને ઇક્વિટી",
    lifestyle_tech: "જીવનશેલી અને ટેક",
    risk_management_cat: "જોખમ સંચાલન",
    other: "અન્ય"
  },
};

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', label: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', label: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', label: 'मराठी', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'gu', label: 'ગુજરાતી', flag: '🇮🇳' },
];

export const t = (lang, key) => strings[lang]?.[key] || strings.en[key] || key;
