export const strings = {
  en: {
    action_blocked: "Action Blocked for Your Protection",
    security_review: "Security Review Required",
    action_approved: "Transaction Approved",
    confirm_after_review: "Confirm After Review",
    cancel_action: "Cancel Action",
    fraud_warning_title: "Fraud Warning",
    helpline_message: "Contact Your Private Banker",
    cooling_off_message: "Cooling-off period active",
    proceed: "Proceed",
    blocked: "ACTION BLOCKED",
    warning: "CAUTION REQUIRED",
    safe: "SAFE ACTION",
    close_logout: "Close and Logout",
    wait: "Wait",
    proceed_anyway: "Proceed Anyway",
    high_risk: "High Probability Fraud Detected",
    elevated_risk: "Elevated Risk",
    low_risk: "Low Risk",
    security_intercept: "Security Intercept",
    account_restricted: "Your account has been temporarily restricted to prevent unauthorized movement of funds.",
  },
  hi: {
    action_blocked: "आपकी सुरक्षा के लिए कार्रवाई अवरुद्ध",
    security_review: "सुरक्षा समीक्षा आवश्यक है",
    action_approved: "लेनदेन स्वीकृत",
    confirm_after_review: "समीक्षा के बाद पुष्टि करें",
    cancel_action: "कार्रवाई रद्द करें",
    fraud_warning_title: "धोखाधड़ी चेतावनी",
    helpline_message: "अपने बैंक हेल्पलाइन से संपर्क करें",
    cooling_off_message: "कूलिंग-ऑफ अवधि सक्रिय",
    proceed: "आगे बढ़ें",
    blocked: "कार्रवाई अवरुद्ध",
    warning: "सावधानी आवश्यक",
    safe: "सुरक्षित कार्रवाई",
    close_logout: "बंद करें और लॉगआउट करें",
    wait: "प्रतीक्षा करें",
    proceed_anyway: "फिर भी आगे बढ़ें",
    high_risk: "उच्च धोखाधड़ी संभावना पकड़ी गई",
    elevated_risk: "उन्नत जोखिम",
    low_risk: "कम जोखिम",
    security_intercept: "सुरक्षा अवरोध",
    account_restricted: "अनधिकृत लेनदेन को रोकने के लिए आपका खाता अस्थायी रूप से प्रतिबंधित किया गया है।",
  },
  ta: {
    action_blocked: "உங்கள் பாதுகாப்பிற்காக செயல் தடுக்கப்பட்டது",
    security_review: "பாதுகாப்பு மதிப்பாய்வு தேவை",
    action_approved: "பரிவர்த்தனை அங்கீகரிக்கப்பட்டது",
    confirm_after_review: "மதிப்பாய்வுக்குப் பிறகு உறுதிப்படுத்தவும்",
    cancel_action: "செயலை ரத்துசெய்",
    fraud_warning_title: "மோசடி எச்சரிக்கை",
    helpline_message: "உங்கள் வங்கி உதவி எண்ணை தொடர்பு கொள்ளவும்",
    cooling_off_message: "குளிர்விக்கும் காலம் செயல்படுகிறது",
    proceed: "தொடர்க",
    blocked: "செயல் தடுக்கப்பட்டது",
    warning: "எச்சரிக்கை தேவை",
    safe: "பாதுகாப்பான செயல்",
    close_logout: "மூடு மற்றும் வெளியேறு",
    wait: "காத்திரு",
    proceed_anyway: "எப்படியும் தொடர்க",
    high_risk: "அதிக மோசடி நிகழ்தகவு கண்டறியப்பட்டது",
    elevated_risk: "உயர் ஆபத்து",
    low_risk: "குறைந்த ஆபத்து",
    security_intercept: "பாதுகாப்பு தடையீடு",
    account_restricted: "அங்கீகரிக்கப்படாத நிதி நகர்வைத் தடுக்க உங்கள் கணக்கு தற்காலிகமாக தடைசெய்யப்பட்டுள்ளது.",
  },
  te: {
    action_blocked: "మీ రక్షణ కోసం చర్య నిరోధించబడింది",
    security_review: "భద్రతా సమీక్ష అవసరం",
    action_approved: "లావాదేవీ ఆమోదించబడింది",
    confirm_after_review: "సమీక్ష తర్వాత నిర్ధారించండి",
    cancel_action: "చర్యను రద్దు చేయి",
    fraud_warning_title: "మోసం హెచ్చరిక",
    helpline_message: "మీ బ్యాంక్ హెల్ప్‌లైన్‌ని సంప్రదించండి",
    cooling_off_message: "కూలింగ్-ఆఫ్ వ్యవధి సక్రియంగా ఉంది",
    proceed: "కొనసాగించు",
    blocked: "చర్య నిరోధించబడింది",
    warning: "జాగ్రత్త అవసరం",
    safe: "సురక్షిత చర్య",
    close_logout: "మూసి లాగ్అవుట్ చేయి",
    wait: "వేచి ఉండు",
    proceed_anyway: "అయినా కొనసాగించు",
    high_risk: "అధిక మోసం సంభావ్యత గుర్తించబడింది",
    elevated_risk: "పెరిగిన ప్రమాదం",
    low_risk: "తక్కువ ప్రమాదం",
    security_intercept: "భద్రతా అడ్డగింత",
    account_restricted: "అనధికార నిధుల చలనాన్ని నిరోధించడానికి మీ ఖాతా తాత్కాలికంగా నిరోధించబడింది.",
  },
  bn: {
    action_blocked: "আপনার সুরক্ষার জন্য কার্যক্রম অবরুদ্ধ",
    security_review: "নিরাপত্তা পর্যালোচনা প্রয়োজন",
    action_approved: "লেনদেন অনুমোদিত",
    confirm_after_review: "পর্যালোচনার পরে নিশ্চিত করুন",
    cancel_action: "কার্যক্রম বাতিল করুন",
    fraud_warning_title: "জালিয়াতি সতর্কতা",
    helpline_message: "আপনার ব্যাংক হেল্পলাইনে যোগাযোগ করুন",
    cooling_off_message: "কুলিং-অফ পিরিয়ড সক্রিয়",
    proceed: "এগিয়ে যান",
    blocked: "কার্যক্রম অবরুদ্ধ",
    warning: "সতর্কতা প্রয়োজন",
    safe: "নিরাপদ কার্যক্রম",
    close_logout: "বন্ধ করুন এবং লগআউট করুন",
    wait: "অপেক্ষা করুন",
    proceed_anyway: "যাইহোক এগিয়ে যান",
    high_risk: "উচ্চ জালিয়াতির সম্ভাবনা সনাক্ত হয়েছে",
    elevated_risk: "উন্নত ঝুঁকি",
    low_risk: "কম ঝুঁকি",
    security_intercept: "নিরাপত্তা বাধা",
    account_restricted: "অননুমোদিত তহবিল স্থানান্তর রোধ করতে আপনার অ্যাকাউন্ট সাময়িকভাবে সীমাবদ্ধ করা হয়েছে।",
  },
  mr: {
    action_blocked: "तुमच्या संरक्षणासाठी कृती अवरोधित",
    security_review: "सुरक्षा पुनरावलोकन आवश्यक",
    action_approved: "व्यवहार मंजूर",
    confirm_after_review: "पुनरावलोकनानंतर पुष्टी करा",
    cancel_action: "कृती रद्द करा",
    fraud_warning_title: "फसवणूक इशारा",
    helpline_message: "तुमच्या बँक हेल्पलाइनशी संपर्क करा",
    cooling_off_message: "कूलिंग-ऑफ कालावधी सक्रिय",
    proceed: "पुढे जा",
    blocked: "कृती अवरोधित",
    warning: "सावधगिरी आवश्यक",
    safe: "सुरक्षित कृती",
    close_logout: "बंद करा आणि लॉगआउट करा",
    wait: "थांबा",
    proceed_anyway: "तरीही पुढे जा",
    high_risk: "उच्च फसवणुकीची शक्यता आढळली",
    elevated_risk: "वाढलेला धोका",
    low_risk: "कमी धोका",
    security_intercept: "सुरक्षा अवरोध",
    account_restricted: "अनधिकृत निधी हस्तांतरण रोखण्यासाठी तुमचे खाते तात्पुरते प्रतिबंधित केले आहे.",
  },
  kn: {
    action_blocked: "ನಿಮ್ಮ ರಕ್ಷಣೆಗಾಗಿ ಕ್ರಿಯೆಯನ್ನು ತಡೆಯಲಾಗಿದೆ",
    security_review: "ಭದ್ರತಾ ಪರಿಶೀಲನೆ ಅಗತ್ಯ",
    action_approved: "ವ್ಯವಹಾರ ಅನುಮೋದಿಸಲಾಗಿದೆ",
    confirm_after_review: "ಪರಿಶೀಲನೆ ನಂತರ ದೃಢೀಕರಿಸಿ",
    cancel_action: "ಕ್ರಿಯೆ ರದ್ದುಗೊಳಿಸಿ",
    fraud_warning_title: "ಮೋಸದ ಎಚ್ಚರಿಕೆ",
    helpline_message: "ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಸಹಾಯವಾಣಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ",
    cooling_off_message: "ತಣಿಸುವ ಅವಧಿ ಸಕ್ರಿಯ",
    proceed: "ಮುಂದುವರಿಸಿ",
    blocked: "ಕ್ರಿಯೆ ತಡೆಯಲಾಗಿದೆ",
    warning: "ಎಚ್ಚರಿಕೆ ಅಗತ್ಯ",
    safe: "ಸುರಕ್ಷಿತ ಕ್ರಿಯೆ",
    close_logout: "ಮುಚ್ಚಿ ಮತ್ತು ಲಾಗ್‌ಔಟ್ ಮಾಡಿ",
    wait: "ನಿರೀಕ್ಷಿಸಿ",
    proceed_anyway: "ಹೇಗಾದರೂ ಮುಂದುವರಿಸಿ",
    high_risk: "ಹೆಚ್ಚಿನ ಮೋಸದ ಸಂಭಾವ್ಯತೆ ಪತ್ತೆಯಾಗಿದೆ",
    elevated_risk: "ಹೆಚ್ಚಿದ ಅಪಾಯ",
    low_risk: "ಕಡಿಮೆ ಅಪಾಯ",
    security_intercept: "ಭದ್ರತಾ ಅಡ್ಡಿ",
    account_restricted: "ಅನಧಿಕೃತ ನಿಧಿ ಚಲನೆಯನ್ನು ತಡೆಯಲು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ತಾತ್ಕಾಲಿಕವಾಗಿ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ.",
  },
  gu: {
    action_blocked: "તમારી સુરક્ષા માટે ક્રિયા અવરોધિત",
    security_review: "સુરક્ષા સમીક્ષા જરૂરી",
    action_approved: "વ્યવહાર મંજૂર",
    confirm_after_review: "સમીક્ષા પછી પુષ્ટિ કરો",
    cancel_action: "ક્રિયા રદ કરો",
    fraud_warning_title: "છેતરપિંડી ચેતવણી",
    helpline_message: "તમારી બેંક હેલ્પલાઇનનો સંપર્ક કરો",
    cooling_off_message: "કૂલિંગ-ઓફ સમયગાળો સક્રિય",
    proceed: "આગળ વધો",
    blocked: "ક્રિયા અવરોધિત",
    warning: "સાવધાની જરૂરી",
    safe: "સુરક્ષિત ક્રિયા",
    close_logout: "બંધ કરો અને લૉગઆઉટ કરો",
    wait: "રાહ જુઓ",
    proceed_anyway: "ગમે તો આગળ વધો",
    high_risk: "ઉચ્ચ છેતરપિંડી સંભાવના શોધી કઢાઈ",
    elevated_risk: "વધેલ જોખમ",
    low_risk: "ઓછ જોખમ",
    security_intercept: "સુરક્ષા અવરોધ",
    account_restricted: "અનધિકૃત ભંડોળ ચળવળ અટકાવવા માટે તમારા ખાતાને અસ્થાયી રૂપે પ્રતિબંધિત કરવામાં આવ્યું છે.",
  },
};

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', label: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', label: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', label: 'मराठी', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'gu', label: 'ગુજરાતી', flag: '🇮🇳' },
];

export const t = (lang, key) => strings[lang]?.[key] || strings.en[key] || key;
